env:
  - DOCKER_IMAGE_APP="justiandre/exemplo-kotlin-paineltarefas:$TRAVIS_BRANCH"

sudo: required

language: kotlin

services:
  - docker

script:
  - docker build -t $DOCKER_IMAGE_APP .
  - docker login -u "$DOCKER_AUTH_USER" -p "$DOCKER_AUTH_PASS"
  - docker push $DOCKER_IMAGE_APP

