# Configuração de log.
logging:
  level:
    org:
      br.com.justiandre: INFO
      apache.http: INFO
      springframework: INFO
      springframework.data.repository: TRACE
      springframework.data.mongodb: TRACE
      springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo: TRACE

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'