# Configuração de log.
logging:
  level:
    org:
      br.com.justiandre: INFO
      apache.http: INFO
      springframework: INFO
      springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo: TRACE